### ISSUE TITLE
出现错误

### ISSUE THREAD

**Issue by QQchu** [Lushenggang/vue-outline#2]
想请问下parentData, level出现错误是什么原因，要怎么解决

**Comment by wintc23** [comment]
具体错误是什么样？ 可以加我微信看看：mask_23




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"QQchu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月24日(星期三) 晚上6:02
收件人:&nbsp;"Lushenggang/vue-outline"<vue-outline@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Lushenggang/vue-outline] 出现错误 (#2)





 
想请问下parentData, level出现错误是什么原因，要怎么解决

**Comment by QQchu** [comment]
我自己的使用上出现了问题 ...大佬还有我想问下，这个小工具只能按selectors的范围使用，如selectors
指定了h1,h2 h3，但内容中没出现了h1，则生成导航会失效，有办法解决吗？想请教下
